import Header from "@/components/layout/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/layout/Footer";
import Filter from "@/components/Filter";
import { Providers } from "@/store/provider";
import { CategoriesFilterServer } from "@/components/manufacturers/filter/CategoriesServer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <>
            <Header />
            <div className="container min-h-screen mx-auto py-4">
              <CategoriesFilterServer />
              {children}
            </div>
            <Footer />
          </>
        </Providers>
      </body>
    </html>
  );
}
