import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { usePathname } from "next/navigation";
import { Toaster } from "sonner";
import Container from "./(main)/layout/Container";
import Header from "./(main)/layout/Header";
import dynamic from "next/dynamic";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NextUIProviderClient = dynamic(
  () => import("@nextui-org/system").then((mod) => mod.NextUIProvider),
  {
    ssr: false,
  }
);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-white dark:bg-slate-900 flex flex-col h-screen`}
      >
        <NextUIProviderClient>
          <Header />
          <main className="container mx-auto py-4 shrink-0">
            {/* {title && pathname != "/" && (
            <h1 class="mb-4 text-3xl font-extrabold leading-tight text-gray-900 lg:mb-6 lg:text-4xl dark:text-white">
              {title}
            </h1>
          )} */}
            {/* {pathname !== "/" && disableBreadcrumbs == false && (
            <Breadcrumbs
              indexText="Главная"
              mainBemClass="breadcrumbs"
              crumbs={customCrumbs}
            />
          )} */}
            <Container>{children}</Container>
          </main>
          {/* <Footer /> */}
          <Toaster richColors />
        </NextUIProviderClient>
      </body>
    </html>
  );
}
